# Default destroyer configuration

input:
  receive: !PathArr
    - test/input/*.jpeg
    - test/input/*.jpg
    - test/input/*.png

output:
  save: !Each
  path: test/output/

  naming: !Original
  format: !Original

progress:
  template: " Elapsed: {elapsed} {wide_bar} {percent}% | Files count: {pos}/{len} "
  chars: "->·"

define:
  - !BilateralFilter
    id: bilateral
    window_size: !Int 3
    sigma_color: !Float 30.0
    sigma_spatial: !Float 30.0

  - !BoxFilter
    id: box
    x_radius: !Int 1
    y_radius: !Int 1

  - !GaussianBlur
    id: gaussian_blur
    sigma: !Float 1

  - !Sharpen3x3
    id: sharpen3x3

  - !SharpenGaussian
    id: sharpen_gaussian
    sigma: !Float 2
    amount: !Float 2

  - !MedianFilter
    id: median
    x_radius: !Int 1
    y_radius: !Int 1

  - !Resize
    id: resize
    width: !Int 300
    height: !Int 200
    filter: !Point

  - !Jpeg
    id: jpeg
    quality: !Int 60

  - !WebP
    id: webp 
    quality: !Int 60 

  - !Brighten
    id: brighten
    value: !Int 10

  - !Contrast
    id: contrast
    contrast: !Float 10

  - !ToLumaAlpha
    id: to_luma_alpha

  - !ToLuma
    id: to_luma

  - !ToRgba
    id: to_rgba

  - !ToRgb
    id: to_rgb

sequence:
  - id: over_compressed
    elements: [!Id webp0-20, !Id jpeg0-20]

  - id: random_blur
    elements: [!RandId [gaussian_blur, box, median]]

  - id: random_sharpen
    elements: [!RandId [sharpen_gaussian, sharpen3x3]]

  - id: random_adjustment
    elements: [!RandId [brighten, contrast]]
  
  - id: gray_webp 
    elements: [!Id to_rgb, !Id webp, !Id to_luma]
  
execute: !Id gray_webp 
